compute_config_id: cpt_v1hkxu5rd61ql5nd268fen83t7
build_id: bld_hu28yb4llwb66fxh3cd9dzh9ty
runtime_env:
  working_dir: "."
  upload_path: "s3://anyscale-temp/diffusion-demo/"
entrypoint: "cd src/service && serve run --non-blocking server_model:entrypoint"
access: "public"